version: '3.11.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  
  app:
    build: .
    container_name: my-flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDatabase
    depends_on:
      - mongo
