version: '3.11.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/myDatabase
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
